### ISSUE TITLE
RSA Secret

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/hippo#15]
If/When we have multiple clusters, store the RSA secret in a key valut like Sloth's SecretsService

**Comment by srkirkland** [comment]
@jSylvestre I assume you mean the RSA secret as the private key for the service account, and not anything to do with they keys for people's logins, correct?

**Comment by jSylvestre** [comment]
@srkirkland Correct, instead of using the userSecrets to store it. Not user's public SSH or login info.
