### ISSUE TITLE
New URL for production

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#155]
As we move toward production, we should move HIPPO to a production URL. I suggest `account.hpc.ucdavis.edu` (or maybe `accounts.hpc`). We control DNS for the hpc subdomain, so we can configure that end, we just need to know what to point it to.

**Comment by jSylvestre** [comment]
@OmenWild We grabbed a prod URL:
https://hippo.ucdavis.edu 
Not sure if everything is configured yet. Think it still has some test data in it.

**Comment by OmenWild** [comment]
I would still like `account.hpc.ucdavis.edu` or `accounts.hpc` to work as well.
