### ISSUE TITLE
Sponsors Cannot Request Accounts

### ISSUE THREAD

**Issue by camillescott** [ucdavis/hippo#166]
If an account has been added as a sponsor, they are marked as having an account already, and hence cannot request account credentials. Also, as with #165, when someone is removed as a sponsor, they are marked as having an account already, even if they never went through the account request flow.

**Comment by srkirkland** [comment]
@camillescott For now I think the best option is to have Sponsors request an account with a designated admin setup as a sponsor.  Once their accounts are approved, you can add them as a sponsor.  We never really considered onboarding for Admins or Sponsors when building the app, so this flow is probably something we should look into when v2 is being planned.

**Comment by sprucely** [comment]
I don't have a specific PR to reference, but this issue has been addressed by the v2 work.
