### ISSUE TITLE
Ability to have sponsors listed multiple times with different Account Names

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#178]
Since the time we talked about requirements the need to have sponsors exist multiple times has changed. PIs already on Farm are now collaborating with other sponsors, also on Farm, to create project type resources (GEMINI and Datalab so far). We need the sponsors to exist to approve access to both their resources, and the group's resources.

**Comment by srkirkland** [comment]
@OmenWild  sounds like because of IS-3 we might want/need to require PIs to have separate accounts for project-type resources.  They would then use these project/group accounts to login when approving/managing group resources, and their personal accounts when managing as themselves.  We should discuss more with Adam.

**Comment by sprucely** [comment]
@OmenWild The sponsor/group changes in the dev branch (see #217 and https://hippo-dev-test.azurewebsites.net) may sufficiently address this. Users can be members and/or admins of multiple groups. I'm not positive, but in the puppet merged yaml, it appeared to me that a lot if not all users have at least one group named after themselves. If a user wants to receive account requests for their personal group, a cluster admin can add their group via the `Groups` tab. Then on the `Group Admins` tab, the user can be made an admin of their own group. After this, the group will appear as an option on the account request page, and the group's user will be notified. Does that sound like it will work for you?

**Comment by sprucely** [comment]
Addressed by V2 changes now in production
