### ISSUE TITLE
As an administrator, I should be able to see the complete list of users and their group associations.

### ISSUE THREAD

**Issue by cbookman** [ucdavis/hippo#180]

**Comment by srkirkland** [comment]
Right now you can see admins and sponsors, but not the users under each sponsor.  I think add a new component which can show all accounts on the system grouped by sponsor in a nice table.  For now, I'd say on the "Sponsored Accounts" page and perhaps also the "Manage Sponsors" page, if the person is an admin, add a link to "View all Accounts" and it can go to that new component.  you can just make a new query in the accountController for it.

**Comment by sprucely** [comment]
In dev branch, `Active Accounts` tab displays all groups and their users that are accessible according to the users' permissions.
