### ISSUE TITLE
Users should have a simple button to click to be able to upload a new SSH key

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#186]
Users should be able to click a button (Upload new SSH public key) that is displayed near this info. Additionally, the SSH key upload should NOT require PI approval.

![image](https://github.com/ucdavis/hippo/assets/686921/ee38fc88-37f4-4274-8da7-3df7f67bd066)

**Comment by sprucely** [comment]
Don't have a specific PR to reference, but this has been addressed during the rollout of V2.
