### ISSUE TITLE
Users getting `Welcome Name you have an account on Farm. Enjoy!` even though they do not

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#195]
Screenshots attached for two different users reporting they are getting the `Welcome Name you have an account on Farm. Enjoy!` even though they do not have an account though hippo at all. One Login ID is `agphinne` and the other is `clmperez`.

At this moment in time, one of those users has submitted an account request, and the other is expected to do so soon.

![Screenshot 2023-06-26 at 11 03 27](https://github.com/ucdavis/hippo/assets/686921/9c3a36e1-1138-4d7a-974a-81d7d6221bcb)
![Screenshot 2023-06-26 at 11 12 48 AM](https://github.com/ucdavis/hippo/assets/686921/c9b10f90-51a0-4044-ba70-a8e84a9af8e0)

**Comment by tefarley** [comment]
I'll circle back to this another time, but what I could find was that these users were erroneously routed from the home component to /<cluster>/<status> instead of /<cluster>/create because their status was already set as such in the db somehow

**Comment by tefarley** [comment]
I have suspicions about where the problem lies, but want to wait and see if another user or I can reproduce this error*
