### ISSUE TITLE
Duplicate accounts

### ISSUE THREAD

**Issue by acgetchell** [ucdavis/hippo#208]
![Screenshot 2023-08-10 at 4 12 39 PM](https://github.com/ucdavis/hippo/assets/434849/44d5a0be-843e-4983-897e-5acb93df8ea3)

**Comment by jSylvestre** [comment]
I believe it is this line that is checking a status of active. That user has several with a status of pending.
https://github.com/ucdavis/hippo/blob/main/Hippo.Web/Controllers/AccountController.cs#L169-L175

**Comment by jSylvestre** [comment]
FYI, list of account with more than 1 that are active.

SELECT TOP (1000) [Id]
      ,[CreatedOn]
      ,[UpdatedOn]
      ,[CanSponsor]
      ,[OwnerId]
      ,[SponsorId]
      ,[IsActive]
      ,[Status]
      ,[Name]
      ,[ClusterId]
      ,[IsAdmin]
  FROM [dbo].[Accounts]
  where OwnerId in (SELECT 
OwnerId
  FROM [dbo].[Accounts]
  where Status = 'Active'
  group by OwnerId, ClusterId
  having count(*) > 1)
  and ClusterId =8
  order by OwnerId

**Comment by jSylvestre** [comment]
![image](https://github.com/ucdavis/hippo/assets/469010/ca8333bd-7a07-45e1-bde7-5f4746e412b9)

**Comment by jSylvestre** [comment]
@tefarley I think this is from your PR:
https://github.com/ucdavis/hippo/pull/184/files

**Comment by acgetchell** [comment]
Doesn't seem to be resolved. There are still duplicate account listings ...

![Screenshot 2023-08-21 at 4 26 22 PM](https://github.com/ucdavis/hippo/assets/434849/334ccfdf-cf99-490c-b25e-a4585f7ecac9)

**Comment by jSylvestre** [comment]
@acgetchell FYI, there are two issues with that.
1. the code causing the duplicates (Should be fixed?)
2. the actual duplicates in the database which may/should be cleaned up. (This might be better left until @sprucely does his database update?)

**Comment by sprucely** [comment]
Right the original cause should be fixed. I'll look at merging the duplicates...

**Comment by tefarley** [comment]
Oh you're right, my bad. I was going through github and closing old issues yesterday and I don't think I meant to close this one.

**Comment by sprucely** [comment]
Okay, the duplicates are fixed. I kept the newest of each group of duplicates (which appears to reflect puppet's state for those accounts) and marked the rest as inactive.

**Comment by acgetchell** [comment]
Awesome, verified, thanks!
