### ISSUE TITLE
HiPPO Producing Non-compliant YAML

### ISSUE THREAD

**Issue by camillescottatwork** [ucdavis/hippo#231]
HiPPO seems to be producing YAMLs sometimes that do not comply with our schema. Recent requests from `tchristi` and `mkeith` came through with `cluster` as a subkey of `sponsor` instead of the newer `meta::cluster` section. I believe this is because generated YAML is being cached in the database as soon as a request is made instead of being generated after approval.

**Comment by sprucely** [comment]
I fixed the yaml in Account records still with a status of `PendingApproval`. New account requests should be fine.  I opened a separate issue for a refactor that will prevent this type of thing happening again.
