### ISSUE TITLE
Allow Open OnDemand users to not submit SSH keys

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#299]
Open OnDemand users auth via CAS through a web site so technically they do not require SSH keys. We may need to add some flexibility to Hippo. My first thought would be to add a drop down with a list like this

What kind of access are you requesting:
* Open OnDemand (web only)
* sbatch/srun/interactive-terminal (SSH to head node)
* Both <- DEFAULT

The 1st option would not require a SSH key, the other 2 would. 

This may create an increased support burden on us when users are confused between the options and don't submit a key when they actually need SSH access. On the other hand, it would prevent users who only need Open OnDemand access from even knowing about SSH keys.

**Comment by sprucely** [comment]
How do we want to indicate in the api the type of access a user is requesting? I'm thinking a list property on `QueuedEventAccountModel` that can have `['SSH']`, `['OpenOnDemand']` or both. You can review the api models at https://hippo.ucdavis.edu/swagger/index.html

**Comment by camillescottatwork** [comment]
There is currently no way to differentiate other than whether they have a public key in the repo, because on-demand only users don't yet exist. An access type property is probably the way to go here.
