### ISSUE TITLE
Web form for HPC Software Install

### ISSUE THREAD

**Issue by cbookman** [ucdavis/hippo#341]
This should not be integrated into the default Hippo workflow .. yet, but we do need it to be CAS enabled.

**Cluster Name:** 
<selection field, with options>
-Farm
-Franklin
-HPC1
-HPC2
-LSSC0
-Peloton

**UC Davis or Affiliate Email:**
<prepopulated with CAS email, editable>

**Account Name on HPC Cluster**
<prepopulated with Kerberos ID, editable>

**Software Title and Version Requested:**
<text field>

**Software License**
<text field>

**Software Home Page:**
<text field>

**How the software will benefit others by making it available to all users:**
<text area>

**Any further information needed?**
<text area>

**Hidden Fields:**
CAS Login ID

**Email to user after submission:**

"Thank you for submitting your request. We appreciate your interest and will begin evaluating the details provided. Our team will review your submission thoroughly and respond as soon as possible.

If we need any further information, we will contact you directly.

Thank you for your patience."

**Email to SNOW after submission to hpc-help@ucdavis.edu** 
Include Web Fields, including the following in the body for consumption by SNOW:

Category: Request
Subcategory: New
Caller: [CAS Login ID]
ConfigurationItem: HPC Software

**Comment by acgetchell** [comment]
We're deprecating certain versions of installed software and need to notify folks. During that notification process, we'd ideally like to link them to [HPCCF's Software installation policy](https://hpc.ucdavis.edu/software-installation-policy), however that contains a link to the intermittently broken SiteFarm site that this feature will replace.

**Comment by sprucely** [comment]
@cbookman Is Hippo supposed to send out three emails? Or does the email sent to [hpc-help@ucdavis.edu](mailto:hpc-help@ucdavis.edu) get forwarded to SNOW?

**Comment by jSylvestre** [comment]
FYI, this is the SN documentation for this:
https://servicehub.ucdavis.edu/servicehub?id=ucd_kb_article&sysparm_article=KB0010800
